# Generated by Django 3.1.3 on 2021-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211114_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
